README.md
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
pubspec.lock
pubspec.yaml

This sets up the release process for Android.

Set up release process

---

lib/app/login/CodeRegisterPage.dart
lib/app/login/PinCodeWidget.dart
pubspec.lock
pubspec.yaml

While testing I noticed our homebrew pin code widget had several issues. Turns out the problem is more complicated than previously thought. This lib has all the corner cases.

Use pin widget library

---

i18n/app_en.arb
lib/app/circle/circle_create_page.dart
lib/services/firebase_providers/firebase_circles_provider.dart

A few things I was able to break :D

Add session count validation and do batch writes

---

i18n/app_en.arb
lib/app/auth.dart
lib/app/circle/circle_create_page.dart
lib/app/circle/circle_page.dart
lib/app/circle/components/circle_participant.dart
lib/app/circle/components/session_item.dart
lib/app/guideline_screen.dart
lib/app/home/components/circle_item.dart
lib/app/home/components/circles_list.dart
lib/app/profile/user_profile_page.dart
lib/components/widgets/index.dart
lib/components/widgets/list_item_container.dart
lib/models/circle.dart
lib/services/auth/firebase_auth_service.dart
lib/services/firebase_providers/firebase_circles_provider.dart

Also fix around schedule of session and DST

user profile integration into the circle information page

---

lib/app/auth.dart
lib/app/circle/circle_create_page.dart
lib/app/guideline_screen.dart
lib/app/home/components/circles_list.dart
lib/app/home/components/topics_list.dart
lib/app/login/components/phone_register_code_entry.dart
lib/app/login/components/phone_register_number_entry.dart
lib/app/login/components/phone_register_number_error.dart
lib/app/login/phone_register_page.dart
lib/app/profile/user_profile_page.dart
lib/app/settings/settings_page.dart
lib/components/widgets/profile_image.dart
lib/models/circle.dart
lib/services/totem_repository.dart
pubspec.lock
pubspec.yaml

This PR updated riverpod to v1.0. A few things got moved and there were some breaking changes. Overall I like the changes as it separates the functionality nicely and feels less magical.
There was also a small bug where the code didn't set `CircleStatus.complete` ever, which crashed the home screen when there are no more sessions.

Update riverpod and other deps

---

android/app/build.gradle
android/build.gradle
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/main.dart
pubspec.lock
pubspec.yaml

Fix #40 - implementation of crashlytics for android and iOS

implemented crashlytics

---

Makefile
android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
ios/Podfile.lock
pubspec.lock
pubspec.yaml

Update Agora, and other things, to latest versions. I ran through the core functionality and everything there works.

Add a bunch of updates

---

.github/workflows/ci.yml
Makefile
lib/app/circle/circle_join_dialog.dart
lib/app/home/home_page.dart
lib/app/profile/user_profile_page.dart
lib/components/camera/profile_image_dialog.dart
lib/components/widgets/profile_image.dart

Use ResizeImage to save some memory. 
Make the Edit Pro file Image modal look more like the Join Circle modal by using similar button layout. 
Allow people to edit their profile image by clicking it in addition to the Edit button. 
Move the Circles header text to the Home location on the home screen.
A few additional cleanups as well.

A few BoFixes. 

---

i18n/app_en.arb
lib/app/login/components/phone_register_number_entry.dart
lib/app/profile/onboarding_profile_page.dart
lib/app/profile/user_profile_page.dart
lib/components/widgets/themed_text_form_field.dart

Feedback from an iOS user where autofill on signup wasn't working as expected.

Add autofill hints

---

.github/workflows/build.yml
.github/workflows/ci.yml
fastlane/Fastfile
fastlane/README.md
ios/Podfile.lock
pubspec.lock
pubspec.yaml

Fix Android CI

---

android/app/src/main/AndroidManifest.xml
lib/services/agora/agora_communication_provider.dart
pubspec.lock

Added Manifest.xml permissions for BLUETOOTH_ADMIN and BLUETOOTH_CONNECT
Add runtime permission requests for both permissions

Fix bluetooth permissions

---

i18n/app_en.arb
lib/app/circle/components/circle_session_controls.dart
lib/services/agora/agora_communication_provider.dart
lib/services/communication_provider.dart

support for next for keeper and removed open floor button

issue #123

---

lib/app/login/components/phone_register_code_entry.dart
lib/app/login/phone_register_page.dart
lib/app/profile/onboarding_profile_page.dart
lib/services/auth/firebase_auth_service.dart

fix to remove guidelines from the sign in workflow
Fix for race condition when auth doesn't go to guideline flow. wasn't waiting for the profile creation to complete first which left a null condition.
Fix #185

Remove guidelines

---

server/functions/src/session.ts

@schalky, is this OK to fix it?

Fix the TS lint for unused key var

---

lib/app/circle/components/circle_live_session_users.dart
lib/app/circle/components/circle_pending_session_users.dart
lib/app/circle/components/layouts.dart
lib/dev/circle_session_test.dart
lib/dev/layouts.dart

Talked to @sebasnieb about making the video in the waiting room larger and centered.

Make waiting room layout video larger, and centered

---

lib/services/agora/agora_communication_provider.dart
pubspec.lock
web/index.html

Small update and defer js for faster loading.

Fix for stopping camera

---

lib/app.dart
lib/main.dart
pubspec.lock
pubspec.yaml

Adds Sentry to instrument the app for both mobile and web

Add sentry for monitoring

---

i18n/app_en.arb

Changed the intro screen title 1 to "Not a Meeting"

Title Change

---

ios/Podfile
ios/Podfile.lock
pubspec.lock

Finally, it looks like all the firebase update issues have been resolved. This is >1 year of updates in one go! I'm sure nothing will go wrong.

Firebase updates

---

lib/services/agora/agora_communication_provider.dart

Disabled switching video resolution when user get/passes totem as this seems to toggle the camera on/off which can create moments of slowness.

Toggling the video quality seems to turn camera off/on

---

lib/app/home/home_page.dart
lib/services/auth/firebase_auth_service.dart

New feature for #243 .
* Added role restriction to "Create Circle". Now only user with the role "keeper" can create a circle.
* Fixed issue with roles not getting loaded on first login.

Issue #243 Restrict create circles to Keepers

---

i18n/app_en.arb
ios/Podfile.lock
lib/app/profile/onboarding_profile_page.dart
lib/components/checkbox_formfield.dart
lib/components/index.dart
lib/dev/dev_page.dart
lib/dev/layouts.dart
lib/models/data_urls.dart
lib/models/user_profile.dart
lib/services/account_state/events/profile_complete_event.dart

Updated onboarding flow to have new check values

---

lib/app/circle/components/speaker_video_view.dart
lib/components/camera/camera_muted.dart

Updated pending totem user to hand mute state

---

lib/app/circle/components/circle_snap_session_content.dart

Fix for preventing close while ending

---

i18n/app_en.arb
lib/app/circle/components/circle_session_controls.dart

Added support for reversing order

---

i18n/app_en.arb
lib/app/circle/components/circle_session_controls.dart

Added a fullscreen mode all by myself! Look at me go.
Only works on web.
Screenshots:
Mobile web
Desktop web
Interested to know if there's a better icon to use?

Add fullscreen to web

---

lib/services/agora/agora_communication_provider.dart

Fix for #261 and #277
* Added function `checkPermissions` to `agora_communication_provider`. This function checks to ensure that for a given permission type (video or audio) the device or browser has the correct permissions and at least one connected device.
* The permissions are handled by the try/catch block. If permission was denied, `deviceManager` will throw an exception. However, if a permission was initially granted and then later revoked through the browser settings, an exception may not be thrown. However, the deviceId will be empty, added `deviceId.isNotEmpty` to handle this case.
* Added `hasAudioPermission` check to `joinSession`. If no audio permission has been given, or there is no connected device, an error will be displayed to the user. This is a requirement for joining, …

Issue #261 and Issue #277 No connected camera fix

---

lib/app/circle/components/circle_snap_session_content.dart

removed the 'circle description' label above the description

fix issue #284

---

lib/services/firebase_providers/firebase_system_provider.dart
server/firebase.json
server/firestore.indexes.json
server/functions/package-lock.json
server/functions/package.json
server/functions/src/common-types.ts
server/functions/src/index.ts
server/functions/src/scheduler.ts
server/functions/src/session.ts

Frontend:
- Fix issue where video initialization would fail if there is no `system` collection (like with local emulator)
Backend:
- Refactor `endSnapCircle` so core functionality can be called separately
- Implement the "scheduler" to run every 5 minutes and check for expired sessions to end
- Test and debug scheduling of expired functions
- Configure pubsub in local emulator
- Realize that scheduled tasks do not work in local emulator ( https://github.com/firebase/firebase-tools/issues/2034)
- Setup mechanism to locally trigger running of scheduled pubsub tasks or run a timeout at regular intervals
- Add support for setting an interim state of `expiring` before ending the session

Ansells issue 323

---

i18n/app_en.arb
lib/app/circle/circle_create_snap_page.dart
lib/models/snap_circle_duration_option.dart
lib/models/snap_circle_visibility_option.dart
lib/services/circles_provider.dart
lib/services/firebase_providers/firebase_circles_provider.dart
lib/services/totem_repository.dart
server/functions/src/session.ts

issue #347 
Make the link to the stage host if we are running against the dev environment
Issue #317 
Backend:
- Handle the `maxMinutes` in options and cap at a max of 60 mins for non-keeper on creating a circle
Frontend:
- Rename `CircleOption` to `CircleVisibilityOption` to avoid confusion with other options
- Add `CircleDurationOption` for creating and formatting time options
- Update `CircleCreateSnapPage` to have a pulldown of duration options (more options for longer circles for keepers)
- Pass the duration down the service chain when creating a circle

Ansells issues #317 #347

---

lib/components/widgets/profile_image.dart

Fixed missing profile image rendering

---

lib/app/circle/circle_session_page.dart
lib/app/circle/components/circle_live_video_session.dart
lib/app/circle/components/pending_totem_user.dart
lib/app/circle/components/speaker_video_view.dart
lib/app/circle/components/totem_action_button.dart
lib/components/widgets/profile_image.dart
lib/models/active_session.dart

fixes #302
clean up of some unused features and centralization of profile to the active session and show tooltip check

support for tooltip for pass

---

lib/services/agora/agora_communication_provider.dart

support for muting on starting/ending/cancelling events

---

lib/app/circle/components/circle_live_session_users.dart

fixes #339 will show next user in the list while waiting for the person to receive the totem

support for keeping the up next user in the list

---

lib/services/firebase_providers/firebase_system_provider.dart

added sort for theme by name

---

lib/services/agora/agora_communication_provider.dart

support for storing/restoring last used devices

---

lib/models/active_session.dart
server/functions/src/common-types.ts
server/functions/src/session.ts

When starting the circle, ensure that the keeper is the first person to go. Fixes #365

Make sure the keeper is the first participant

---

i18n/app_en.arb
lib/app/circle/circle_session_page.dart
lib/app/circle_create/circle_create_non_keeper.dart
lib/app/circle_create/index.dart
lib/app/home/components/create_circle_button.dart
lib/app/home/home_page.dart

Fixes #385
User is only prompted with duration and number of users then goes into the join flow. Private circles skip the info dialog step unless they are no longer running.

Added support for quicker private non-keeper circle creation

---

lib/components/widgets/themed_control_button.dart

Hover state and pressed state for control buttons

---

i18n/app_en.arb
lib/app/circle/components/circle_live_video_session.dart
lib/app/circle/components/circle_session_timer.dart
lib/components/widgets/countdown_timer.dart
lib/services/firebase_providers/firebase_session_provider.dart
lib/services/session_provider.dart
lib/services/totem_repository.dart
server/functions/src/common-types.ts
server/functions/src/session.ts

Issue #400 Add time to running session
Backend:
- Implement cloud function `addMinutesToSession`
- Fixed name of `expiresOn` field Frontend:
- Refactor the session time into its own widget `CircleSessionTimer`
- Add menu for keeper with option to "modify time" and "end now"
- Implement dialog for adding time
- Add interfaces to call cloud function for adding time to session

Issue #400
